plugins:
  swiftlint:
    enabled: true
exclude_patterns: 
  - "Example/"
  - "Tests/"
  - "Configs/"
  - "Carthage/"
  - "fastlane/"
  - "*.yml"
  - ".gitignore"
  - ".swift-version"
  - "LICENSE"
  - "*.md"
  - "*.podspec"
  - "*.xcodeproj"