branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode9.3
language: swift

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
  - carthage build --no-skip-current
  - pod lib lint
  - fastlane test
  - fastlane coverage
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
