branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode9.3
language: swift

script: 
  - carthage build --no-skip-current
  - fastlane scan
  - pod lib lint
  
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'WhatsNewKit'
