name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download Codeclimate Test-Reporter
      run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
    - name: Update access rights for Test-Reporter
      run: chmod +x ./cc-test-reporter
    - name: Before-Build Test-Reporter
      run: ./cc-test-reporter before-build
    - name: Perform Test
      run: fastlane test
    - name: Gather Code-Coverage
      run: fastlane coverage
    - name: Format Code-Coverage for Test-Reporter
      run: ./cc-test-reporter format-coverage -t cobertura
    - name: Upload Code-Coverage to CodeClimate
      run: ./cc-test-reporter after-build -r ${{ secrets.CC_TEST_REPORTER_ID }}
